
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
cds:
  data-source.auto-config.enabled: false
  remote.services:
    Northwind_Service:
      type: "odata-v2"
      model: "Northwind_Service"
      destination:
        properties:
          url: https://services.odata.org/V2/Northwind/Northwind.svc/
          authentication: NoAuthentication
---
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
