
---
spring:
  config.activate.on-profile: cloud
  sql.init.platform: h2
cds:
  data-source.auto-config.enabled: false
  remote.services:
    Northwind_Service:
      type: "odata-v2"
      model: "Northwind_Service"
      http:
        service: "/Northwind.svc"
      destination:
        properties:
          url: https://services.odata.org/V2/Northwind/
          authentication: NoAuthentication
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
